### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by de-roo** [arduino-libraries/Arduino_LPS22HB#4]
The code here and the code that is installed with the Arduino Desktop IDE 1.8.13 are both v. 1.0.0, but are not the same.  
The library installed directly from within the IDE does not correctly wait for the one-shot measurement to complete, and so reports old data (which is why the first measurement is always bad), while this library on GitHub does wait.  
I suspect that if the version number of this GitHub repository was updated the better code would be more widely distributed, esp. for newbies.

**Comment by aentinger** [comment]
Done :heavy_check_mark: - https://github.com/arduino-libraries/Arduino_LPS22HB/releases/tag/1.0.1
